# Generated by Django 3.0.6 on 2020-05-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name_plural': 'Meals'},
        ),
    ]
