# Generated by Django 3.0.6 on 2020-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservations'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default='your Email', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='your Name', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_persons',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
